### ISSUE TITLE
Infinite fails

### ISSUE THREAD

**Issue by davidweichiang** [diprism/perpl#100]
This should have a sum-product of 1:

```
data Nat = Zero | Succ Nat;

define equal = \m. \n. case m of
  | Zero -> (case n of
    | Zero -> ()
    | Succ n' -> fail)
  | Succ m' -> (case n of
    | Zero -> fail
    | Succ n' -> equal m' n');

define random = amb Zero (Succ random);

equal random Zero
```

but using `perplc -z` it hangs.

**Comment by ccshan** [comment]
Hmm but `perplc -c | perplc -z` gives `[1.0]`!

**Comment by ccshan** [comment]
The automatically generated discard functions for (defunctionalized) Nat, which are unused and infinite, seem to be at fault: If I temporarily change `affLinDiscards` to `return` in `Transform/Afflin.hs`, then `perplc -z` gives `[1.0]` as desired.

**Comment by ccshan** [comment]
Is it completed...?
