### ISSUE TITLE
rules/nonterminals are being generated for externs

### ISSUE THREAD

**Issue by davidweichiang** [diprism/perpl#122]

**Comment by davidweichiang** [comment]
There ought to be a test case to ensure that externs are translated correctly, but it's not easy right now.

**Comment by davidweichiang** [comment]
Ah, this is my fault. I don’t remember why, but I needed to change the translation of extern calls so that they have their own rule. But the nonterminal and terminal now have the same name, which is an error.

**Comment by davidweichiang** [comment]
Cf #27

**Comment by HerbertMcSnout** [comment]
I think this issue is more widespread than just externs... It looks like constructors also have both nonterminal and terminal entries in the FGG json too
