### ISSUE TITLE
Doesn't this program almost surely terminate?

### ISSUE THREAD

**Issue by ccshan** [diprism/perpl#60]
This program, **without** commenting out the two lines, is an attempt at flipping coins in search of HTH:
```
data Flip = H | T;
data Flips = Cons Flip Flips;
data Unit = unit;
define flips = Cons (sample uniform) flips;
define search = \fs: Flips.
  case fs  of | Cons f1 fs1 -> if f1 == T then search fs1 else
  -- case fs1 of | Cons f2 fs2 -> if f2 == H then search (Cons H fs2) else
  -- case fs2 of | Cons f3 fs3 -> if f3 == T then search (Cons T (Cons T fs3)) else
  unit;
search flips
```
But [the compiled FGG](https://github.com/diprism/fgg-implementation/files/8679720/hth.txt) gives `[0.0]`. Commenting out the second line, [to search for HT instead](https://github.com/diprism/fgg-implementation/files/8679733/ht.txt), also gives `[0.0]`. Commenting out both lines, [to search for just H](https://github.com/diprism/fgg-implementation/files/8679736/h.txt), gives `[1.0]` as desired.

**Comment by davidweichiang** [comment]
Also, the fact that it worked for H suggests that the problem isn’t the
infinite stream per se…
