### ISSUE TITLE
`TpData` should have tags and params as two separate lists

### ISSUE THREAD

**Issue by davidweichiang** [diprism/perpl#93]
> Come to think of it, if `DefCtor` and `DefData` have tags and params as two separate `[Var]`s (which makes sense), then `TpData` should have tags and params as two separate lists as well (`[Var]` and `[Type]` I guess).

_Originally posted by @ccshan in https://github.com/diprism/perpl/issues/79#issuecomment-1198845332_

**Comment by davidweichiang** [comment]
I still think that because tags are used only during type inference, it'd be nicer not to have to drag that (usually empty) list of tags through all the other phases. I'm still hoping that we can distinguish tag and type variables as different cases so we can store them in a single list everywhere...

**Comment by ccshan** [comment]
But the single list (or both lists) are empty after monomorphization, right?

**Comment by davidweichiang** [comment]
RIght.

**Comment by davidweichiang** [comment]
This also affects `TmCase` and the return value of `ctxtLookupType2` (sorry for my terrible naming).

**Comment by davidweichiang** [comment]
And `TmVarG`

**Comment by davidweichiang** [comment]
Closed by #102
