### ISSUE TITLE
Identity factors

### ISSUE THREAD

**Issue by davidweichiang** [diprism/perpl#97]
There are several places where sparse factors are created for packing/unpacking tuples or variants, which need to be made more efficient. I think there are just two kinds:

```
{
  "function": "directsum",
  "type": [ "a+b", "a" ],
  "sizes": [ 123, 456 ]
}
```

```
{
  "function": "tensorproduct",
  "type": [ "(a,b)", "a", "b" ],
  "sizes": [ 123, 456 ]
}
```

**Comment by ccshan** [comment]
What about equality, is it eliminated by some optimization already, or a special case of both of these kinds?

**Comment by davidweichiang** [comment]
I was thinking it’s a special case of both kinds.

**Comment by ccshan** [comment]
For proper directsum and tensorproduct factors (as opposed to equality aka identity aka diagonal factors), I hope torch-semiring-einsum doesn't mind handling input tensors that are views on other tensors (i.e., with non-default stride and/or non-zero offset)?
